project:
  type: website
  execute-dir: project
  render: # Add HERE new chapters and new notebooks
    - index.qmd
    - chapters/chapter1.qmd
    - chapters/chapter2.qmd
    - notebooks/notebook1.qmd

website:
  page-navigation: true
  title: "A quick test of the Python template"
  # In the two URLs below:
  # - replace AIML4OS by the Github account/organization your repository is hosted by;
  # - replace AIML4OS-template-quarto-python by the name of your repository.
  # If your repo is on the AIML4OS organization, change only the name of the repo.
  site-url: "https://oliviermeslin.github.io/quick_test"
  repo-url: "https://github.com/oliviermeslin/quick_test"
  repo-actions: [edit, source, issue]
  sidebar:
    search: true
    contents: # Add HERE new chapters (but not the notebooks)
      - href: index.qmd
        text: Introduction
      - href: chapters/chapter1.qmd
        text: A complete example
      - href: chapters/chapter2.qmd
        text: A new chapter

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    code-fold: true
  ipynb:
    output: true


filters:
  - export-metadata.lua

